name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  key:
    description: 'nostr private key'
    required: true
  relay:
    description: 'nostr relay'
    required: true
    default: 'wss://relayer.fiatjaf.com'
  content:
    description: 'nostr content'
    required: true
    
outputs:
  eventHash:
    description: 'The hash of the published event'
runs:
  using: 'node12'
  main: 'dist/index.js'
