name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  relay:
    description: 'nostr relay'
    required: true
    default: 'wss://relayer.fiatjaf.com'
  content:
    description: 'nostr relay'
    required: true
    
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node12'
  main: 'dist/index.js'
