name: nostr

on:
  workflow_dispatch:
    inputs:
      content:
        description: content (e.g. hello world!)
        required: true
      relay:
        description: relay
        type: choice
        options: 
        - wss://nostr-pub.wellorder.net
        - wss://relayer.fiatjaf.com
        - wss://nostr.rocks
        - wss://rsslay.fiatjaf.com
        - wss://nostr-relay.herokuapp.com
        - wss://freedom-relay.herokuapp.com/ws
        - wss://nodestr-relay.dolu.dev/ws
        - wss://nostrrr.bublina.eu.org
        - wss://nostr-relay.freeberty.net
        - wss://nostr.bitcoiner.social
        - wss://nostr-relay.wlvs.space

jobs:
  units:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish event via nostr
        uses: theborakompanioni/nostr@v1
        with:
          relay: ${{ github.event.inputs.relay }}
          content: ${{ github.event.inputs.content }}
