name: nostr

on:
  workflow_dispatch:
    inputs:
      key:
        description: private key (e.g. 0123456789abcdef...)
        required: true
      relay:
        description: relay (e.g. wss://relayer.fiatjaf.com)
        type: choice
        options: 
        - wss://nostr-pub.wellorder.net
        - wss://relayer.fiatjaf.com
        - wss://nostr.rocks
        - wss://rsslay.fiatjaf.com
        - wss://nostr-relay.herokuapp.com
        - wss://freedom-relay.herokuapp.com/ws
        - wss://nodestr-relay.dolu.dev/ws
        - wss://nostrrr.bublina.eu.org
        - wss://nostr-relay.freeberty.net
        - wss://nostr.bitcoiner.social
        - wss://nostr-relay.wlvs.space
      content:
        description: content (e.g. hello world!)
        required: true

jobs:
  units:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish event via nostr
        uses: ./
        with:
          key: ${{ github.event.inputs.key }}
          relay: ${{ github.event.inputs.relay }}
          content: ${{ github.event.inputs.content }}
